### ISSUE TITLE
curve25519-java is GPLv3-licensed

### ISSUE THREAD

**Issue by Vampire** [codahale/xsalsa20poly1305#1]
When checking license compatibility, I found that you have `org.whispersystems:curve25519-java:0.3.1` as dependency.
That library is released under GPLv3.
This means as long as you don't release your own code under GPLv3 too or switch to a curve implementation that is compatible with ASL, you are infringing copyrights.

**Comment by Vampire** [comment]
Ar actually I'm not sure whether you are violating the GPL, but at least as long as you have a GPL-dependency you force anyone that wants to release a product with your lib and the dependency in it to release their stuff under GPL or **they**  would at least violate GPL otherwise, so if you stay with that dependency, you could as well release your lib under GPL to make it at least clear that currently a consumer of your lib has to release under GPL.

But while not being a lawyer, as far as I have ready, the lib itself should also count a derivative work already.

**Comment by codahale** [comment]
Björn, given that you’re not a lawyer, I’d suggest you refrain from using potentially threatening legal language when discussing these kinds of issues. I’m assuming good intent but telling people they’re “infringing copyrights” or “violating the GPL” is a really bad way to start a discussion like this.

First, the GPLv3’s trigger condition applies to the redistribution of code or the compiled artifacts based on code — specifically, it requires licensees to provide the original source code, retain the license and all copyright information, and allow usage of said code according to the license. I’m not redistributing Whisper Systems’ library, though. The source code is not in this repository, nor are any compiled artifacts. I am not violating the GPL, and I’d appreciate it if you did more homework before accusing me or others of such.

Second, I think you are correct that if you redistributed a copy of Whisper Systems’ library and did not meet the conditions of the GPLv3, you would be in violation of the license. That seems very much like your problem, however, and I suggest you consult a lawyer with experience in software licensing.

Third, “derivative work” is a [specific term of legal art](https://en.wikipedia.org/wiki/Derivative_work) which does not mean what you think it means:

> A “derivative work” is a work based upon one or more preexisting works, such as a translation, musical arrangement, dramatization, fictionalization, motion picture version, sound recording, art reproduction, abridgment, condensation, or any other form in which a work may be recast, transformed, or adapted. A work consisting of editorial revisions, annotations, elaborations, or other modifications which, as a whole, represent an original work of authorship, is a “derivative work”.

This library is not a derivative work of Whisper Systems’ library.

Fourth, if you’d like to do the work of porting this library over to a Curve25519 implementation which has a more liberal license, I would accept that PR.

**Comment by codahale** [comment]
As it happens, Bouncy Castle added X25519 support in their last release, and porting it over was super simple. I’ve released 0.9.0, which only depends on Bouncy Castle.

That said, I really wish you’d opened an issue with _your_ problem — that having a GPLv3-licensed dependency makes you nervous or the software you’re working on needs this — instead of half-baked legal analysis. Remember, when you open an issue like this you’re asking a human to take some time out of their day to do free work for you. It’s a lot easier and rewarding for me to do that when I know I’m helping another human with their day.

**Comment by Vampire** [comment]
I'm really sorry if you felt attacked, I just wanted to inform you of the situation.
You are right, I'm no laywer, but your software depended on that curve library to work and thus it is discutable whether it is derivative work.
I still think it was a grey zone and _at least_ it was confusing to your users if they think they depend on ASL2 software and indeed depend on GPLed software.

Anyway, I'm glad you could solve it that easily and reacted that fast.
Many thanks for your work.
And sorry again if you feel offended. I assumed you just didn't notice and wanted to inform you.

**Comment by codahale** [comment]
To be clear: it is absolutely not a derivative work. There is no ambiguity on this whatsoever. As I mentioned before, that is a specific term in US IP law. It means something else.

Either way, I agree the situation was confusing and I’m happy I could quickly resolve it.
